on:
  push:
    branches:
      - main
      - action-test
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"


jobs:
  build:
    strategy:
      matrix:
        platform:
          - windows-latest
        architecture:
          - x64
          - arm64
          - x86

    runs-on: ${{ matrix.platform }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');         

  
      - name: Get git submodules
        run: git submodule update --init --recursive
  
      - name: Set architecture
        run: echo "ARCHITECTURE=${{ matrix.architecture }}" >> $GITHUB_ENV
  
      - name: Install dependents
        run: |
          choco install ninja -y
  
      # - name: Install vcpkg
      #   run: |
      #     git clone https://github.com/Microsoft/vcpkg.git
      #     cd vcpkg
      #     .\bootstrap-vcpkg.bat
      #     .\vcpkg integrate install
  
      # - name: Cache
      #   uses: actions/cache@v3
      #   with:
      #       path: |
      #         ./vcpkg
      #         ./vcpkg_installed
      #       key: ${{ runner.os }}-${{ env.BUILD_TYPE }}-${{ hashFiles('./vcpkg.json')}}
      #       restore-keys: |
      #         vcpkg-
  
      - name: Install vcpkg package
        run: |
          vcpkg install 
          vcpkg integrate install


      # - name: Save vcpkg Cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ./vcpkg
      #     key: ${{ runner.os }}-${{ env.BUILD_TYPE }}-${{ hashFiles('**/CMakeLists.txt') }}-${{ hashFiles('./vcpkg.json')}}
  
      - name: Configure CMake
        run: |
          mkdir build
          cmake -S . -B  ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE="$Env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -GNinja
        working-directory: ${{github.workspace}}
        
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.architecture }}-${{ env.BUILD_TYPE }}
          path: ${{github.workspace}}/build/bin/*